name: CI

on:
  push:
  pull_request:
  repository_dispatch:
    types: [run_build]

jobs:
  build:
    strategy:
      matrix:
        debug: [all, debug]
    runs-on: ubuntu-latest
    container: ps2dev/ps2toolchain:latest
    steps:
      - uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          apk add build-base git bash

      # Still compilation is not fully compatible with multi-thread
      - name: Compile project ${{ matrix.debug }}
        run: |
          make -j $(getconf _NPROCESSORS_ONLN) clean
          make -j 1 ${{ matrix.debug }}
          make -j $(getconf _NPROCESSORS_ONLN) install
          ln -sf "$PS2SDK/ee/lib/libcglue.a" "$PS2DEV/ee/mips64r5900el-ps2-elf/lib/libcglue.a"
          ln -sf "$PS2SDK/ee/lib/libpthreadglue.a" "$PS2DEV/ee/mips64r5900el-ps2-elf/lib/libpthreadglue.a"
          ln -sf "$PS2SDK/ee/lib/libkernel.a"  "$PS2DEV/ee/mips64r5900el-ps2-elf/lib/libkernel.a"
          ln -sf "$PS2SDK/ee/lib/libcdvd.a"  "$PS2DEV/ee/mips64r5900el-ps2-elf/lib/libcdvd.a"

      - name: Compile samples
        if: ${{ success() }}
        run: |
          cp -rv $PS2SDK/samples ~/
          make -C ~/samples
          
      - name: move IRX
        if: ${{ success() }}
        run: |
          mv $PS2SDK/iop/irx/ ~/IOP/
          zip -q 9 IRX.zip ~/IOP/*.*

      - name: Get short SHA
        id: slug
        run: echo "sha8=$(echo ${GITHUB_SHA} | cut -c1-8)" >> $GITHUB_OUTPUT

      - name: Upload artifacts
        if: ${{ success() }}
        uses: actions/upload-artifact@v3
        with:
          name: ps2sdk-samples-${{ matrix.debug }}-${{ steps.slug.outputs.sha8 }}
          path: |
            ~/samples
            ~/IOP/

      - name: Create release
        if: github.ref == 'refs/heads/download-irx'
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: ${{ format('{0}_{1}', 'IRX', matrix.debug) }}
          title: "latest IRX Binaries"
          files: |
            ~/IRX.zip
